name: IT academy Homework 11 - mkolchyn

on: 
  push:
  workflow_dispatch:
jobs:
  itacad_hw-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Build and push WCG Docker image
        run: |
          repository_owner=${{ github.repository_owner }}
          repository_owner_lowercase=$(echo "$repository_owner" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${repository_owner_lowercase}/wcg:${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/wcg:latest -f Dockerfile.multi .
          docker push ghcr.io/${repository_owner_lowercase}/wcg:${{ github.sha }}
          docker push ghcr.io/${repository_owner_lowercase}/wcg:latest
