Vagrant.configure("2") do |config|
  config.vm.hostname = "03-ansible"
  config.vm.box = "generic/debian10"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "name" do |name|
#    ansible.vm.network "private_network", ip: "192.168.50.5"

    name.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.become = true
    end
  end
end