Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "jenkins_ansible" do |jenkins_ansible|
    jenkins_ansible.vm.network "private_network", ip: "192.168.50.25"
    jenkins_ansible.vm.hostname = "jenkins-ansible"

    jenkins_ansible.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"
    end
  end

end 