Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.50.25"
    jenkins.vm.hostname = "jenkins"
  end

  config.vm.define "jenkins_ansible" do |jenkins_ansible|
    jenkins_ansible.vm.network "private_network", ip: "192.168.50.26"
    jenkins_ansible.vm.hostname = "jenkins-ansible"

    jenkins_ansible.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "nexus" do |nexus|
    nexus.vm.network "private_network", ip: "192.168.50.30"
    nexus.vm.hostname = "nexus"
  end

  config.vm.define "nexus_ansible" do |nexus_ansible|
    nexus_ansible.vm.network "private_network", ip: "192.168.50.31"
    nexus_ansible.vm.hostname = "nexus_ansible"

    nexus_ansible.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end

  config.vm.define "staging" do |staging|
    staging.vm.network "private_network", ip: "192.168.50.40"
    staging.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    staging.vm.hostname = "staging"
    staging.vm.provision "shell", inline: <<-SHELL
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
        echo -e "vagrant\nvagrant" | passwd vagrant
    SHELL
  end

  config.vm.define "production" do |production|
    production.vm.network "private_network", ip: "192.168.50.50"
    production.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    production.vm.hostname = "production"
    production.vm.provision "shell", inline: <<-SHELL
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
        echo -e "vagrant\nvagrant" | passwd vagrant
    SHELL
  end

end 