Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.50.25"
    master.vm.hostname = "master"
    
  #   master.vm.provision "ansible_local" do |ansible|
  #     ansible.install_mode = "pip"
  #     ansible.playbook = "playbook.yml"
  #   end
  end

  config.vm.define "slave1.puppet" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.26"
    slave.vm.network "forwarded_port", guest: 80, host: 8080
    slave.vm.hostname = "slave1"

    # slave.vm.proexitvision "ansible_local" do |ansible|
    #   ansible.install_mode = "pip"
    #   ansible.playbook = "playbook.yml"
    # end
  end

  config.vm.define "slave2.puppet" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.27"
    slave.vm.network "forwarded_port", guest: 81, host: 8081
    slave.vm.hostname = "slave2"

  #   slave.vm.provision "ansible_local" do |ansible|
  #     ansible.install_mode = "pip"
  #     ansible.playbook = "playbook.yml"
  #   end
  end
end 