---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      imagePullSecrets:
        - name: github-pull-secret

      containers:
        - name: wcg
          image: ghcr.io/mkolchyn/wcg
          imagePullPolicy: Always
          resources: {}