Vagrant.configure("2") do |config|
  config.vm.hostname = "temp"
  config.vm.box = "generic/debian10"
  config.vm.synced_folder ".", "/vagrant"

config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.name = "temp"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
  sudo apt update
  sudo apt install -y lxc
  sudo systemctl start lxc
  sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 10.0.100.100:80
  sudo iptables -t nat -A PREROUTING -p tcp --dport 81 -j DNAT --to-destination 10.0.100.101:80
  iptables -t nat -A POSTROUTING -j MASQUERADE
  # sudo apt install -y iptables-persistent
  sudo su -
  echo 'export DOWNLOAD_KEYSERVER="hkp://keyserver.ubuntu.com"' >> /root/.bashrc
  exec bash  

# container Static 
  lxc-create -t download -n static -- -d centos -r 8-Stream -a amd64
  cp /vagrant/config_static /var/lib/lxc/static/config
  lxc-start static
  
#   # cp /vagrant/index.html /var/lib/lxc/static/rootfs/var/www/html/

# # container Dynamic   
#   lxc-create -t download -n dynamic -- -d centos -r 8-Stream -a amd64
#   cp /vagrant/config_dynamic /var/lib/lxc/dynamic/config
#   lxc-start dynamic
#   # lxc-attach dynamic
#   # yum install -y httpd
#   # yum install -y php

  # cp /vagrant/index.php /var/lib/lxc/dynamic/rootfs/var/www/html/

SHELL

end