Vagrant.configure("2") do |config|
  config.vm.hostname = "hometask-1-1"
  config.vm.box = "generic/debian9"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.name = "hometask-1.1"
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y apache2
    sudo apt install -y php
    sudo mkdir /var/www/php/
    sudo chmod -R o+w /var/www/
    sudo chmod -R o+w /etc/apache2/
  SHELL

  config.vm.provision "file", source: "./index.html", destination: "/var/www/html/"
  config.vm.provision "file", source: "./index.php", destination: "/var/www/php/"
  config.vm.provision "file", source: "./ports.conf", destination: "/etc/apache2/"
  config.vm.provision "file", source: "./000-default.conf", destination: "/etc/apache2/sites-available/"

  config.vm.provision "shell", inline: "sudo systemctl restart apache2"
end